language: rust
sudo: false
cache: cargo

matrix:
  include:
  - rust: beta
    env: RUST_BACKTRACE=1
    addons:
      firefox: latest
      chrome: stable
    before_script:
      - curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh -s -- -f
    script:
      - cargo check
      - cargo test
      - wasm-pack build
#      - wasm-pack test --chrome --firefox --headless
